language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt
  - pip install codecov
  - python -m sc.app.startup
  - python -m sc.tests.smtpserver &

script:
  - coverage run -m sc.tests.bundle

branches:
  only:
    - master
  
after_success:
  - codecov