language: python
python:
  - "2.7"

stages:
  - name: after_success
    if: branch = master

install: 
  - pip install -r requirements.txt
  - pip install codecov
  - python -m shakecast.app.startup
  - python -m shakecast.tests.smtpserver &

script:
  - coverage run -m shakecast.tests.bundle
  - python setup.py bdist_wheel
  
after_success:
  - codecov

deploy:
  - provider: pypi
    user: "dslosky"
    password: $PYPI_PASSWORD
    distributions: "bdist_wheel"
    on:
      tags: true