version: '3.1'

services:
  sc-server:
    build:
      context: .
      dockerfile: sc-server.dockerfile
    networks:
      - sc-network
    volumes:
      - "/data/pycast/db:/usr/local/shakecast/sc/db"
      - "/data/pycast/eq_data:/usr/local/shakecast/sc/data"
      - "/data/pycast/tmp:/usr/local/shakecast/sc/tmp"
      - "/data/pycast/conf:/usr/local/shakecast/sc/conf"
      - "/data/pycast/templates:/usr/local/shakecast/sc/templates"
  
  web-server:
    build:
      context: .
      dockerfile: web-server.dockerfile
    ports:
      - "80:80"
    networks:
      - sc-network
    volumes:
      - "/data/pycast/db:/usr/local/shakecast/sc/db"
      - "/data/pycast/eq_data:/usr/local/shakecast/sc/data"
      - "/data/pycast/tmp:/usr/local/shakecast/sc/tmp"
      - "/data/pycast/conf:/usr/local/shakecast/sc/conf"
      - "/data/pycast/templates:/usr/local/shakecast/sc/templates"

networks:
  sc-network:
    driver: bridge
