version: '3'

services:
  sc-server:
    build:
      context: .
      dockerfile: sc-server.dockerfile
    ports:
      - "1981:1981"
    networks:
      - sc-network
    volumes:
      - "~/pycast/db:/usr/local/shakecast/shakecast/db"
      - "~/pycast/eq_data:/usr/local/shakecast/shakecast/data"
      - "~/pycast/tmp:/usr/local/shakecast/shakecast/tmp"
      - "~/pycast/conf:/usr/local/shakecast/shakecast/conf"
      - "~/pycast/templates:/usr/local/shakecast/shakecast/templates"
      - "~/pycast/logs:/usr/local/shakecast/shakecast/logs"
      - "~/pycast/local_products:/usr/local/shakecast/shakecast/local_products"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    restart: unless-stopped
  
  web-server:
    build:
      context: .
      dockerfile: web-server.dockerfile
    ports:
      - "80:5000"
    networks:
      - sc-network
    volumes:
      - "~/pycast/db:/usr/local/shakecast/shakecast/db"
      - "~/pycast/eq_data:/usr/local/shakecast/shakecast/data"
      - "~/pycast/tmp:/usr/local/shakecast/shakecast/tmp"
      - "~/pycast/conf:/usr/local/shakecast/shakecast/conf"
      - "~/pycast/templates:/usr/local/shakecast/shakecast/templates"
      - "~/pycast/logs:/usr/local/shakecast/shakecast/logs"
      - "~/pycast/local_products:/usr/local/shakecast/shakecast/local_products"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    restart: unless-stopped

networks:
  sc-network:
    driver: bridge
