# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: centos-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install codecov
        python -m shakecast.app.startup
        python -m shakecast.tests.smtpserver &
    - name: Test
      run: |
        coverage run -m shakecast.tests.bundle
        codecov
    - name: Test install
      run: |
        sudo python -m shakecast start &
        curl localhost
        
